/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.robovm.libimobiledevice.binding;

public class ScreenShotrClientRefOut {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ScreenShotrClientRefOut(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ScreenShotrClientRefOut obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LibIMobileDeviceJNI.delete_ScreenShotrClientRefOut(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ScreenShotrClientRef getValue() {
    long cPtr = LibIMobileDeviceJNI.ScreenShotrClientRefOut_value_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ScreenShotrClientRef(cPtr, false);
  }

  public ScreenShotrClientRefOut() {
    this(LibIMobileDeviceJNI.new_ScreenShotrClientRefOut(), true);
  }

}
