/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.robovm.libimobiledevice.binding;

public enum ScreenShotrError {
  SCREENSHOTR_E_SUCCESS(0),
  SCREENSHOTR_E_INVALID_ARG(-1),
  SCREENSHOTR_E_PLIST_ERROR(-2),
  SCREENSHOTR_E_MUX_ERROR(-3),
  SCREENSHOTR_E_BAD_VERSION(-4),
  SCREENSHOTR_E_UNKNOWN_ERROR(-256);

  public final int swigValue() {
    return swigValue;
  }

  public static ScreenShotrError swigToEnum(int swigValue) {
    ScreenShotrError[] swigValues = ScreenShotrError.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (ScreenShotrError swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + ScreenShotrError.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private ScreenShotrError() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private ScreenShotrError(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private ScreenShotrError(ScreenShotrError swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

