/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.robovm.libimobiledevice.binding;

public class ScreenShotrClientRef {
  private transient long swigCPtr;

  protected ScreenShotrClientRef(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected ScreenShotrClientRef() {
    swigCPtr = 0;
  }

  protected static long getCPtr(ScreenShotrClientRef obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

