/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.robovm.libimobiledevice.binding;

public class SyslogRelayClientRef {
  private transient long swigCPtr;

  protected SyslogRelayClientRef(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SyslogRelayClientRef() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SyslogRelayClientRef obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

