/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.robovm.llvm.binding;

public class AttributeArray {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected AttributeArray(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AttributeArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LLVMJNI.delete_AttributeArray(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setValue(AttributeRef value) {
    LLVMJNI.AttributeArray_value_set(swigCPtr, this, AttributeRef.getCPtr(value), value);
  }

  public AttributeRef getValue() {
    long cPtr = LLVMJNI.AttributeArray_value_get(swigCPtr, this);
    return (cPtr == 0) ? null : new AttributeRef(cPtr, false);
  }

  public AttributeArray(int nelements) {
    this(LLVMJNI.new_AttributeArray(nelements), true);
  }

  public AttributeRef get(int index) {
    long cPtr = LLVMJNI.AttributeArray_get(swigCPtr, this, index);
    return (cPtr == 0) ? null : new AttributeRef(cPtr, false);
  }

  public void set(int index, AttributeRef value) {
    LLVMJNI.AttributeArray_set(swigCPtr, this, index, AttributeRef.getCPtr(value), value);
  }

}
