/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.robovm.llvm.binding;

public class AttributeRefOut {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected AttributeRefOut(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AttributeRefOut obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LLVMJNI.delete_AttributeRefOut(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public AttributeRef getValue() {
    long cPtr = LLVMJNI.AttributeRefOut_value_get(swigCPtr, this);
    return (cPtr == 0) ? null : new AttributeRef(cPtr, false);
  }

  public AttributeRefOut() {
    this(LLVMJNI.new_AttributeRefOut(), true);
  }

}
