/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.robovm.llvm.binding;

public interface LLVMConstants {

  public final static String _DEFAULT_TARGET_TRIPLE = "x86_64-apple-darwin18.5.0";
  public final static int _ENABLE_THREADS = 1;
  public final static int _HAS_ATOMICS = 1;
  public final static String _HOST_TRIPLE = "x86_64-apple-darwin18.5.0";
  public final static int _ON_UNIX = 1;
  public final static int _USE_INTEL_JITEVENTS = 0;
  public final static int _USE_OPROFILE = 0;
  public final static int _USE_PERF = 0;
  public final static int _VERSION_MAJOR = 8;
  public final static int _VERSION_MINOR = 0;
  public final static int _VERSION_PATCH = 0;
  public final static String _VERSION_STRING = "8.0.0";
  public final static int _FORCE_ENABLE_STATS = 0;
}
