/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.robovm.llvm.binding;

public enum UnnamedAddr {
  NoUnnamedAddr,
  LocalUnnamedAddr,
  GlobalUnnamedAddr;

  public final int swigValue() {
    return swigValue;
  }

  public static UnnamedAddr swigToEnum(int swigValue) {
    UnnamedAddr[] swigValues = UnnamedAddr.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (UnnamedAddr swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + UnnamedAddr.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private UnnamedAddr() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private UnnamedAddr(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private UnnamedAddr(UnnamedAddr swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

